# Generated by Django 5.2.3 on 2025-09-12 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_vendor_scoped_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricerangemargin',
            name='dont_pay_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
