# Generated by Django 5.2.3 on 2025-09-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_vendor_scoped_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='method_type',
            field=models.CharField(default='api', max_length=20),
        ),
    ]
